FROM ghcr.io/puppeteer/puppeteer:20.11.1

RUN apk add chromium

WORKDIR /app
COPY package*.json ./
RUN npm ci --verbose
COPY ./ ./
RUN npm run build
EXPOSE 8080
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
CMD ["npm", "start"]